#!/bin/sh
#
#	camp - Cygwin / Apache / MySQL / PHP startup script
#
DbUser='root'
DbPass='root'
CygSrv="CygServer"
SrvCnf=/etc/cygserver.conf
Prg=`basename $0`

ErrExit()
{
    echo "$1" >&2
    exit $2
}

Usage()
{
    ErrExit "Usage: $Prg start|stop|install|remove|status" 1
}

ChkAdmin()
{
    id | grep Admin >/dev/null && return
    ErrExit "$Prg: must be run as Administrator" 2
}

ChkInstall()
{
    cygrunsrv -L | grep "$CygSrv" >/dev/null && return
    ErrExit "$Prg: not installed" 4
}

ChkCygrun()
{
    cygrunsrv -Q "$CygSrv" | grep 'Running' >/dev/null
}

ChkProc()
{
    ps -ef | grep "[s]bin/$1" >/dev/null
}

MysqlCtl()
{
    case "$1" in
	start)	mysqld_safe >/var/log/mysqld_safe.log 2>&1 & ;;
	stop)	mysqladmin -u$DbUser -p$DbPass shutdown ;;
    esac
}

for pkg in httpd mysqld httpd-mod_php5
do
    cygcheck -c $pkg | grep "^$pkg " >/dev/null || ErrExit "$Prg: $pkg package is not installed" 3
done

test "$1" || Usage
case $1 in
    install)
	cygrunsrv -L | grep "$CygSrv" >/dev/null && ErrExit "$Prg: already installed" 5
	ChkAdmin
	test -f $SrvCnf || { echo "Setting up cygserver."; cygserver-config -n; }
	echo "Installing cygserver as a Windows service."
	cygrunsrv -I "$CygSrv" -p /usr/sbin/cygserver.exe -t manual -O -d "Cygwin IPC and security"
	echo "Run \"mysql_install_db\" to install mysql default databases"
	echo "Run \"$Prg start\" to start $Prg services"
	;;
    remove)
	ChkInstall
	ChkAdmin
	echo "Removing cygserver Windows service."
	cygrunsrv -R "$CygSrv"
	rm -f $SrvCnf
	;;
    start)
	Runs="is already running"
	Msg="Starting Cygwin"
	ChkInstall
	ChkAdmin
	ChkCygrun && echo "Cygwin Service $Runs" || { echo "$Msg Service"; cygrunsrv -S "$CygSrv"; }
	ChkProc httpd && echo "Cygwin Apache $Runs" || { echo "$Msg Apache"; /usr/sbin/apachectl start; }
	ChkProc mysqld && echo "Cygwin mysqld $Runs" || { echo "$Msg mysqld"; MysqlCtl start; }
	;;
    stop)
	Stop="is not running"
	Msg="Stopping Cygwin"
	ChkInstall
	ChkAdmin
	ChkProc mysqld && { echo "$Msg mysqld"; MysqlCtl stop; } || echo "Cygwin mysqld $Stop"
	ChkProc httpd && { echo "$Msg Apache"; /usr/sbin/apachectl stop; } || echo "Cygwin Apache $Stop"
	ChkCygrun && { echo "$Msg Service"; cygrunsrv -E "$CygSrv"; } || echo "Cygwin Service $Stop"
	;;
    status)
	test -f $SrvCnf && cond="" || cond=" not"
	echo "Cygserver is$cond configured"
	test "$cond" && exit 1
	ChkCygrun && cond="" || cond=" not"
	echo "Cygwin Service is$cond running"
	ChkProc httpd && cond="" || cond=" not"
	echo "Cygwin Apache is$cond running"
	ChkProc mysqld && cond="" || cond=" not"
	echo "Cygwin mysqld is$cond running"
	;;
    *)
	Usage
	;;
esac
exit 0
